travis:
  secure:
    BINSTAR_TOKEN: 17MhkWqKtjNMbvYtuaaSj1HAykeer/UXBXErR+jt0x7ZLqgLavEr++2+kD7ryOiQJ9XEIy5LQTjQnp1X0a+qPRLWu5k2csNkICKvdwZoNf/NcHd4+hUIfqHmKmVwhSNGD5n4KJDnbtf9UdwnUuVqv/ozlYOPDVQAP0RwvA8F4sO3jOiUJtB6UInkcwQGn6yOKMFgNTPlIx+0ZQa9p1Q3TK/gutCvBgp9tM0avjFYC3f8f/8uxMK0rInbFYbGAk+YuH9Y96nGOYONPGLUkowXCRH6WDmQ8YupkY3h2xbznBzji0ZFMiKSMTOwmap4M+JfUEk+qxOeuHsJc/Kpnev+MkexlD2a61S6kSMYWl2rTFlgXyzPXCjz9seipWwJQS+Snt5oTbE3U8r5fMSwX74/mMq7p7My6jszXBOqSGEei9fe68ftOmPfDmrOUxjWKtB46z+/HU35SsYiKN0V5qUWf1cZkjnwT1CqUMNQ983SbVGnEiwq/3RHQC65zDlYaKiwFlqdQgMdoSxo/pINfVpsZp4Hra9iRvD4VJCKG15siIfv+FSOLV+tc22+9cot9+gB8PHbxPDHUbJO/BlN0u2ljs/X5IVfXqq6twSE5qTSUSLYstwcQ7IctpHkEQLx3iYBYhAiyWh6Ly1UzFGhEez5WN1ItO3qk4Pjcdx6Bsko5GY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
